### ISSUE TITLE
Add ability for user to add sdr scaling factor vs freq vs gain

### ISSUE THREAD

**Issue by MichaelCotton** [NTIA/scos-sensor#119]
@linhvu1 is setting up a calibration procedure for the sensors. Step 1 is to measure the sdr scaling factor. Pls add ability for user (admin) to input sdr scaling factor vs freq array.

**Comment by ToddSchumann** [comment]
Given how much the scale factor changes, I'd recommend this be done with a CSV file (either uploading it through the SCOS manager or having the calibration generate it in a location which isn't cleared when a new image is loaded for the sensor). This is how I loaded them in sdr_calibrator (which uses the `csv` library):
'''
        # Check if these should be loaded from a file
        if self.profile.test_scale_factor_definition_file:
            try:
                f0s = []
                sfs = []
                fname = self.profile.test_scale_factor_definition_file
                with open(fname, 'rb') as f:
                    reader = csv.reader(f, delimiter=',')
                    for row in reader:
                        f0s.append(float(row[0]))
                        sfs.append(float(row[1]))
                    f.close()
'''

**Comment by djanderson** [comment]
Some work on this was merged in abc76efde, keeping it open because it still needs a test case.

Essentially anything that is likely to change (like scale factor) is held in the database on the sensor so that it can be modified via the Configuration admin interface. It could also be initialized into the database via a script and a csv file, which would probably be really helpful if that's what your calibration routine outputs. Otherwise it would have to be input by hand.

**Comment by MichaelCotton** [comment]
Propose scos-sensor have the capability to read csv file that defines sfs(f0, sdr_gain) matrix instead of sfs(f0) at a single sdr_gain.

@linhvu1 Pls post here the plot of measured SDR dynamic range and noise figure vs `sdr_gain`. 

We had a long discussion today about this plot. Basically, we are converging on a process where the B210 should only be used in a range of sdr_gain, i.e., [`sdr_gain_min`, `sdr_gain_max`]:
- above `sdr_gain_max` B210 shouldn't be used bc dynamic range is too small
- below `sdr_gain_min` B210 shouldn't be used bc noise figure is too large

From plot, you can see that there is only 20 or so sdr_gain settings that should be used (down from 76 or something that the B210 makes available. Rather than measuring an array sfs(f0) at a single sdr_gain, we decided to measure the matrix sfs(f0, sdr_gain), within [`sdr_gain_min`, `sdr_gain_max`]. Otherwise, we are picking a somewhat arbitrary operating point. There is variability as a fct of sdr_gain.

**Comment by ToddSchumann** [comment]
I'm working on the file format the scale factor file as I'll need to use it in the calibrator scripts as well. This is what I was thinking (feel free to suggest otherwise):

[CSV Scale Factor File]
`1  `[gain1],[gain2],...
`2  `List of the scale factor division frequencies
`3  `[freq1],[SF at freq1/gain1],[SF at freq1,gain2],...
`4  `[freq2],[SF at freq2/gain1],[SF at freq2/gain2],...

This should allow us to interpolate the SF by frequency or f0 as required later and stay within the specific divisions so we don't get any errors as we cross the divisions. For applying the scale factor, this is how I foresee the algorithm:

1. Determine which division the current f0 is in
2. Interpolate between the two nearest scale-factor points for this division with a weighted average (if it is beyond an endpoint for a division, just use the end point scale factor)

**Comment by linhvu1** [comment]
![figure_1](https://user-images.githubusercontent.com/5238437/42228047-347eb156-7ea0-11e8-8eb2-b366248acad1.jpg)

**Comment by djanderson** [comment]
Yes I think that's a great idea. @ToddSchumann it might be useful to test parsing your csv file format with python's `csv` reader.  Another option is to use JSON for ingest, something like:

```json
[
    {
        "gain": 30,
        "frequency": 400e6,
        "scale_factor": 1.12
    },
    {
        "gain": 30,
        "frequency": 500e6,
        "scale_factor": 1.25
    }
]
```
which is quite readable... thoughts?

**Comment by djanderson** [comment]
Fxied by e178b8504.
