### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by earldean** [NTIA/scos-sensor#121]
https://github.com/NTIA/scos-sensor/blob/6764ca324fe9e28692608b410efb64af07086777/src/schedule/serializers.py#L173

I think this was suppose to say 'stop time is not later than start'

**Comment by djanderson** [comment]
Right on. Go ahead and push that through, though all the greyhounds are currently set to track master IIRC so you'll likely want to SSH into them and do a `cd /opt/scos-sensor && ./scripts/backup_{location,capabilities}.sh greyhound` first so that you can `./scripts/restore_fixture.sh ../src/{status,capabilities}/fixtures/greyhound-2018-05-30` afterwards.
