### ISSUE TITLE
Laboratory calibration / supporting different sensor hardware configs

### ISSUE THREAD

**Issue by MichaelCotton** [NTIA/scos-sensor#124]
There are two types of calibrations: laboratory and onboard sensor.  The onboard-sensor calibration process is performed at the sensor and all metadata/data will be captured in `YFactorCalibration` object. Greyhound sensors, however, have no calibration signal source. Plus, all sensors need to be calibrated in the lab before being deployed.

We need to define and document the laboratory calibration process and scos-sensor functions to support. Strawman laboratory y-factor calibration process:
1. Connect calibrated noise source into sensor antenna port
2. Specify sigmf-ns-scos/`Antenna`: `model` = `"Keysight xxxx"`, `type` = `"calibrated noise source"`, ...
3. Turn OFF power to calibrated noise source
4. Run scos-sensor `Action` to acquire P_off data at full operational frequency range 
5. Turn ON power to calibrated noise source
6. Run scos-sensor `Action` to acquire P_on data at full operational frequency range
7. Iterate for range of `receiver_setting`, e.g., `"attenuation"`
8. Calculate noise figure and gain

Note 1: sigmf-ns-scos/`Antenna` might need to be adapted to support step 2

Notes on scos-sensor `Action` to laboratory y-factor calibration: 
1. This cal process should automated with an external code base, so scos-senor `Action` should only be simple IQ capture at specified frequencies
2. Full operational frequency range will be different for each sensor hardware configuration, e.g., operational frequency range will depend on sdr and can be limited by RF filters in preselector.
3. For sensor with a wide open front end, strawman measurement procedure is to step across receiver frequency range at 100 MHz steps

Should @linhvu1 + fork scos-sensor and create greyhound repo with actions and documentation that are specific for greyhound, e.g., laboratory calibration actions?

This leads to the bigger question: how do we support different in-house and 3rd party:
1. sensor hardware builds
2.  sensor algorithms

**Comment by aromanielloNTIA** [comment]
Closing this since it's outdated and has been addressed.

- Y-Factor calibration action with preselector API support has been added. The Y-Factor behavior is a bit different than described here (it doesn't exhaust all sigan parameters by default, though it can be configured to do so). The Y-Factor action is also not a simple IQ capture, but it does leverage common DSP functions in the SCOS Actions signal processing library.
- SigMF-NS-NTIA has been updated to support recording of calibration data, sensor hardware, and sensor algorithm results
