### ISSUE TITLE
Investigate divide-by-zero warning in power linear->log conversion

### ISSUE THREAD

**Issue by djanderson** [NTIA/scos-sensor#20]
```=============================== warnings summary ===============================
acquisitions/tests/test_archive_view.py::test_archive_download
  /home/dja/git/scos-sensor/src/actions/acquire_single_freq_fft.py:197: RuntimeWarning: divide by zero encountered in log10
    fdata_dbm_m4s = 10 * np.log10(fdata_watts_m4s) + 30 + Vsq2W_dB

-- Docs: http://doc.pytest.org/en/latest/warnings.html
```

**Comment by ToddSchumann** [comment]
The back-end algorithm for `np.log10` will use a divide by the arguement, so somehow to the variable `fdata_watts_m4s` is zero in this case. The easiest way to handle this I believe would be to watch for this error and replace `fdata_watts_m4s` with the power of the noise floor since that should be the lowest power measured. I'm not sure why `fdata_watts_m4s` is beinf calculated as zero yet. Could it be an error in a previous step which sets it to `False`?

**Comment by djanderson** [comment]
@kenbaker do you have any comments on this? Looks like the divide-by-zero error is happening around the area you've been investigating. Is the right approach to catch and replace w/ noise floor?

**Comment by kenbaker** [comment]
I'll take a look next week. It had never occurred to me until you raised this issue that we (anyone) should pay attention to this possibility ... and look for ways to mitigate.  I'll take a look at why fdata_watts_m4s might be zero too ... as per Todds 7/2 comment.  We might be able to reorder or rework that sum so that it does not go to zero.
